# Copyright (C) 2015 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/jfltedcm/setup-makefiles.sh

## jfltedcm/common-proprietary-files.txt
PRODUCT_COPY_FILES += \
    vendor/samsung/jfltedcm/proprietary/bin/efsks:system/bin/efsks \
    vendor/samsung/jfltedcm/proprietary/bin/ks:system/bin/ks \
    vendor/samsung/jfltedcm/proprietary/bin/qcks:system/bin/qcks \
    vendor/samsung/jfltedcm/proprietary/bin/qmuxd:system/bin/qmuxd \
    vendor/samsung/jfltedcm/proprietary/bin/rild:system/bin/rild \
    vendor/samsung/jfltedcm/proprietary/bin/rmt_storage:system/bin/rmt_storage \
    vendor/samsung/jfltedcm/proprietary/lib/libatparser.so:system/lib/libatparser.so \
    vendor/samsung/jfltedcm/proprietary/lib/libdsutils.so:system/lib/libdsutils.so \
    vendor/samsung/jfltedcm/proprietary/lib/libfactoryutil.so:system/lib/libfactoryutil.so \
    vendor/samsung/jfltedcm/proprietary/lib/libidl.so:system/lib/libidl.so \
    vendor/samsung/jfltedcm/proprietary/lib/libnetmgr.so:system/lib/libnetmgr.so \
    vendor/samsung/jfltedcm/proprietary/lib/libomission_avoidance.so:system/lib/libomission_avoidance.so \
    vendor/samsung/jfltedcm/proprietary/lib/libqcci_legacy.so:system/lib/libqcci_legacy.so \
    vendor/samsung/jfltedcm/proprietary/lib/libqmi.so:system/lib/libqmi.so \
    vendor/samsung/jfltedcm/proprietary/lib/libqmi_client_qmux.so:system/lib/libqmi_client_qmux.so \
    vendor/samsung/jfltedcm/proprietary/lib/libqmiservices.so:system/lib/libqmiservices.so \
    vendor/samsung/jfltedcm/proprietary/lib/libreference-ril.so:system/lib/libreference-ril.so \
    vendor/samsung/jfltedcm/proprietary/lib/libril-qcril-hook-oem.so:system/lib/libril-qcril-hook-oem.so \
    vendor/samsung/jfltedcm/proprietary/lib/libril.so:system/lib/libril.so \
    vendor/samsung/jfltedcm/proprietary/lib/libsecril-client.so:system/lib/libsecril-client.so \
    vendor/samsung/jfltedcm/proprietary/vendor/lib/libdiag.so:system/vendor/lib/libdiag.so \
    vendor/samsung/jfltedcm/proprietary/vendor/lib/libqmi_cci.so:system/vendor/lib/libqmi_cci.so \
    vendor/samsung/jfltedcm/proprietary/vendor/lib/libqmi_common_so.so:system/vendor/lib/libqmi_common_so.so \
    vendor/samsung/jfltedcm/proprietary/vendor/lib/libqmi_csi.so:system/vendor/lib/libqmi_csi.so \
    vendor/samsung/jfltedcm/proprietary/vendor/lib/libqmi_encdec.so:system/vendor/lib/libqmi_encdec.so
